export const copy = {
  appName: '本地生活',
  nav: {
    home: '首页',
    shops: '商户',
    nearby: '附近',
    vouchers: '优惠',
    blogs: '探店',
    hot: '热榜',
    login: '登录',
  },
  login: {
    title: '短信登录',
    phoneLabel: '手机号',
    codeLabel: '验证码',
    phonePlaceholder: '请输入手机号',
    codePlaceholder: '请输入验证码',
    sendCode: '发送验证码',
    sending: '发送中…',
    submit: '立即登录',
    submitting: '登录中…',
    agreement: '登录即表示同意平台服务协议与隐私说明。',
    success: '登录成功，欢迎回来。',
    required: '请先完成登录后再继续操作。',
    tips: '未登录也可以先浏览首页、商户、附近和热榜内容。',
  },
  home: {
    heroTitle: '发现身边好店与优惠',
    heroSubtitle: '先逛再决定，登录后即可抢券、签到和互动。',
    heroCtaPrimary: '开始浏览商户',
    heroCtaSecondary: '查看附近热门',
    sectionTitle: '一站式本地生活入口',
    sectionSubtitle: '从找店、看评价到领优惠，公开内容先看清楚，再决定是否登录参与。',
    highlights: [
      '公开商户与优惠信息，先了解再行动。',
      '登录后可继续抢券、签到、发布与互动。',
      '统一中文引导，减少陌生页面的理解成本。',
    ],
  },
  shops: {
    listTitle: '精选商户',
    detailTitle: '商户详情',
    nearbyTitle: '附近商户',
    empty: '当前暂无可展示的商户，稍后再来看看。',
    locationDenied: '未获得定位权限，已为你展示默认商户列表。',
    browseHint: '首页、商户详情与附近商户支持匿名浏览。',
    pricePrefix: '人均',
    scorePrefix: '评分',
    distancePrefix: '距离',
    typeTitle: '商户分类',
    detailNotFound: '未找到对应商户，请稍后重试。',
  },
  vouchers: {
    title: '限时优惠',
    subtitle: '先了解活动节奏，登录后再参与抢购与签到。',
    empty: '暂无进行中的优惠活动。',
    heroTitle: '公开查看活动，合适再出手',
    heroBody: '活动列表支持先浏览再决策，登录后即可一键抢券并同步签到。',
    statusUpcoming: '即将开始',
    statusActive: '进行中',
    statusEnded: '已结束',
    statusSoldOut: '已抢完',
    payLabel: '秒杀价',
    actualLabel: '门店价',
    stockLabel: '剩余库存',
    windowLabel: '活动时间',
    claimNow: '立即抢券',
    claimDone: '领取成功',
    claimSuccess: '领取成功，优惠券已加入你的活动记录。',
    browseHint: '未登录也可先浏览活动信息与价格对比。',
  },
  blogs: {
    feedTitle: '探店内容流',
    feedSubtitle: '浏览大家最近的真实探店记录，决定下一站去哪里。',
    publishTitle: '发布探店笔记',
    publishSubtitle: '整理你的真实体验，登录后即可补充图文内容。',
    hotTitle: '点赞热榜',
    hotSubtitle: '看看最近最受欢迎的探店内容和商户口碑。',
    empty: '暂时还没有新的探店内容。',
    feedHeroTitle: '真实探店内容，帮你更快做决定',
    feedHeroBody: '公开内容流支持先浏览、先判断，登录后再继续发布、点赞和关注。',
    hotHint: '热榜公开可见，互动动作会在需要时再引导登录。',
    publishSuccess: '发布成功，新的探店笔记已经加入内容流。',
    titleLabel: '标题',
    contentLabel: '内容',
    shopIdLabel: '关联商户 ID',
    submit: '发布笔记',
    submitting: '发布中…',
    like: '点赞',
    liked: '已点赞',
    follow: '关注',
    unfollow: '取消关注',
    commonEmpty: '你和目标用户暂时还没有共同关注。',
  },
  follows: {
    title: '共同关注',
    subtitle: '登录后可查看你与目标用户共同关注的账号。',
    heroTitle: '看看你们关注了哪些同路人',
    heroBody: '共同关注可以帮助你快速发现口味接近、推荐相似的用户。',
  },
  common: {
    loading: '加载中，请稍候…',
    empty: '暂无数据',
    retry: '重新加载',
    browseFirst: '公开内容已为你准备好，登录后再继续互动。',
    loginPromptTitle: '登录后继续',
    loginPromptBody: '该操作需要先完成短信登录，你仍可继续浏览公开内容。',
    loginPromptAction: '去登录',
  },
  stats: {
    openShops: '开放浏览商户',
    activityZones: '活跃板块',
    loginPromise: '登录后能力',
  },
  actions: {
    viewDetail: '查看详情',
    goShops: '去看商户',
    goNearby: '查看附近',
    goVouchers: '浏览优惠',
    goLogin: '短信登录',
    exploreBlogs: '浏览探店',
    viewHot: '查看热榜',
    publishBlog: '发布探店',
    signToday: '今日签到',
    signedToday: '今日已签到',
    refreshActivity: '刷新活动',
    loadMore: '继续浏览',
  },
  labels: {
    businessHours: '营业时间',
    protectedFeature: '登录后解锁',
    publicBrowse: '公开浏览',
  },
  status: {
    loginSuccessHint: '验证码校验通过后会自动进入下一步页面。',
    codeSent: '验证码已发送，请查看后端日志或测试环境返回结果。',
    activityLoading: '正在同步活动数据，请稍候。',
    signStreakPrefix: '已连续签到',
    signStreakSuffix: '天',
  },
  marketing: {
    trustTitle: '先了解，再决定是否互动',
    trustBody: '首页、商户、附近、优惠与热榜内容支持公开浏览，抢券、签到、发布与关注会在需要时再引导登录。',
  },
  errors: {
    network: '网络开小差了，请稍后重试。',
    unauthorized: '当前操作需要登录后才能进行。',
    invalidPhone: '请输入正确的手机号。',
    invalidCode: '验证码无效或已过期。',
    activityLoad: '活动信息加载失败，请稍后重试。',
    signLoad: '签到信息加载失败，请稍后重试。',
    blogLoad: '探店内容加载失败，请稍后重试。',
    blogPublish: '探店内容发布失败，请稍后重试。',
    followLoad: '共同关注加载失败，请稍后重试。',
  },
} as const

export type AppCopy = typeof copy
